"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['menu_temp.py']
DATA_FILES = []
OPTIONS = {
    'plist': {
        'LSUIElement': True,  # Hide Dock icon
    },
    'packages': ['rumps', 'requests'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
